---
- name: Configure Windows Server
  hosts: windows
  gather_facts: no

  tasks:
    - name: Install IIS and Start Service
      win_feature:
        name: Web-Server
        state: present

    - name: Create User Accounts
      win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        groups: "{{ item.groups }}"
      loop: "{{ user_accounts }}"

    - name: Configure Firewall Rules
      win_firewall_rule:
        name: "Allow HTTP"
        direction: in
        action: allow
        protocol: tcp
        localport: 80

    - name: Install .NET Framework
      win_chocolatey:
        name: dotnet5.0
        state: present
      when: ansible_facts['os_family'] == 'Windows'

    - name: Create Scheduled Task
      win_scheduled_task:
        name: "My Scheduled Task"
        description: "My scheduled task description"
        actions:
          - path: "powershell.exe"
            arguments: "-command \"Write-Output 'Hello from My Scheduled Task'\""
        triggers:
          - type: daily
            start_time: "00:00"
            random_delay: "00:00:30"
            frequency: daily
            interval: 1
            enabled: true
      when: ansible_facts['os_family'] == 'Windows'
