---
- name: Display and Save Running Services on Windows
  hosts: win1.example.com
  gather_facts: no

  tasks:
    - name: Get running services
      win_shell: Get-Service | Where-Object { $_.Status -eq 'Running' } | ConvertTo-Html | Out-File "$env:USERPROFILE\Desktop\running_services.html"
