---
- name: Windows Server Configuration
  hosts: win1.example.com
  gather_facts: no

  tasks:
    - name: Get System Information
      win_shell: |
        $systemInfo = Get-CimInstance Win32_ComputerSystem
        $osInfo = Get-CimInstance Win32_OperatingSystem

        $html = @"
        <h1>System Information</h1>
        <table>
        <tr><th>Computer Name</th><td>$($systemInfo.Name)</td></tr>
        <tr><th>Manufacturer</th><td>$($systemInfo.Manufacturer)</td></tr>
        <tr><th>Model</th><td>$($systemInfo.Model)</td></tr>
        <tr><th>OS Version</th><td>$($osInfo.Caption) $($osInfo.Version) ($($osInfo.OSArchitecture))</td></tr>
        </table>
        "@

        $html | Out-File "$env:USERPROFILE\Desktop\health_check_report.html"

    - name: Get Software Information
      win_product_facts:
      register: software_info

    - name: Print Software Information
      debug:
        var: software_info

    - name: Create User Accounts
      win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop:
        - { name: "user1", password: "password1" }
        - { name: "user2", password: "password2" }

    - name: Install IIS and Start Service
      win_feature:
        name: Web-Server
        state: present

    - name: Configure Firewall Rules
      win_firewall_rule:
        name: "Allow HTTP"
        direction: in
        action: allow
        protocol: tcp
        localport: 80

    - name: Create Scheduled Task
      win_scheduled_task:
        name: "My Scheduled Task"
        description: "My scheduled task description"
        actions:
          - path: "powershell.exe"
            arguments: "-command \"Write-Output 'Hello from My Scheduled Task'\""
        state: present

    - name: Ensure Service is Running
      win_service:
        name: "MyService"
        state: started
