---
- name: Windows Server Configuration
  hosts: win1.example.com
  gather_facts: no

  tasks:
    - name: Get System Information
      # Health check tasks from the previous playbook

    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Check IIS status
      win_service:
        name: W3SVC
        state: started

    - name: Save Combined Report
      win_shell: |
        $html = @"
        <h1>Combined Health Check and IIS Installation Report</h1>
        "@

        # Include the health check HTML
        $html += Get-Content "$env:USERPROFILE\Desktop\health_check_report.html"

        # Add an additional section for IIS installation status
        $html += @"
        <h2>IIS Installation Status</h2>
        <p>IIS installation and service status: {%- if ansible_win_service_state_W3SVC == 'started' %}Running{%- else %}Not Running{%- endif %}</p>
        "@

        # Save the combined report
        $html | Out-File "$env:USERPROFILE\Desktop\combined_report.html"
