---
- name: Example Playbook for Windows
  hosts: win1.example.com
  gather_facts: no

  tasks:
    - name: Perform a Windows task
      win_command: Get-Process
      register: process_output

    - name: Display Windows task output
      debug:
        var: process_output.stdout_lines
