---
- name: Install Microsoft SQL Server
  hosts: win1.example.com
  gather_facts: no

  tasks:
    - name: Install SQL Server
      win_chocolatey:
        name: sql-server-express
        state: present
      become: yes